services:
    havvg_jasmine.fixtures_controller:
        class: Havvg\Bundle\JasmineBundle\Controller\FixturesController
        arguments:
            - "%havvg_jasmine.fixtures.directory%"

    havvg_jasmine.routing.loader:
        class: Havvg\Bundle\JasmineBundle\Routing\JasmineLoader
        calls:
            - [ setDirectory, [ "%havvg_jasmine.fixtures.directory%" ] ]
            - [ setWebPath, [ "%havvg_jasmine.fixtures.web_path%" ] ]
        tags:
            - { name: 'routing.loader' }

    havvg_jasmine.routing.cache_clearer:
        class: Havvg\Bundle\JasmineBundle\Routing\CacheClearer
        arguments:
            - "%havvg_jasmine.fixtures.web_path%"
        tags:
            - { name: 'kernel.cache_clearer' }
